// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrbbtozuqvdpohrpuicf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhyYmJ0b3p1cXZkcG9ocnB1aWNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MjA1NDMsImV4cCI6MjA2MTQ5NjU0M30.sk9gVvVIB67d1kdHuW2hUOYnhzESgK5hV4izLexYHMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);